/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class circus_CFunctions */

#ifndef _Included_circus_CFunctions
#define _Included_circus_CFunctions
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     circus_CFunctions
	 * Method:    injectMouseMovement
	 * Signature: (II)V
	 */
	JNIEXPORT void JNICALL Java_circus_CFunctions_injectMouseMovement
	(JNIEnv*, jobject, jint x, jint y);

	JNIEXPORT void JNICALL Java_circus_CFunctions_injectKeyboardInput
	(JNIEnv*, jobject, jstring input);

#ifdef __cplusplus
}
#endif
#endif
